[package]
name = "too_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
too = { git = "https://github.com/museun/too", branch = "too_lua", features = [ "profile" ] }

# NOTE the minimum supported lua is 5.3 (for integers)
mlua = { version = "0.10.3", features = [ "lua54", "error-send" ] }
slotmap = "1.0.7"
profiling = "1.0.16"

[dev-dependencies]
fastrand = "2.3.0"
profiling = { version = "1.0.16", features = [ "profile-with-puffin" ] }
puffin_http = "0.16.1"
